import ast
import contextlib
import functools
import hashlib
import io
import random
import re

import pytest

from qdojo import hashing, riddle as R, riddles

SEEDS = range(30)
ALL_KINDS = [(belt, kind) for belt in riddles.BELTS for kind in riddles.kinds(belt)]


# --------------------------------------------------------------------------
# shape, validation, canonical answers, determinism

def test_belts_and_kinds():
    assert riddles.BELTS == ("white", "yellow", "orange", "green", "blue")
    for belt in riddles.BELTS:
        ks = riddles.kinds(belt)
        assert ks and len(set(ks)) == len(ks)
    assert len(riddles.kinds("white")) >= 4
    assert len(riddles.kinds("yellow")) >= 4
    assert len(riddles.kinds("orange")) >= 4
    assert len(riddles.kinds("green")) >= 3
    with pytest.raises(riddles.RiddleGenError):
        riddles.kinds("black")
    with pytest.raises(riddles.RiddleGenError):
        riddles.generate_kind("no_such_kind", random.Random(0), 1)


@pytest.mark.parametrize("belt", riddles.BELTS)
def test_every_belt_generates_valid_riddles(belt):
    seen = set()
    for seed in SEEDS:
        d = riddles.generate(belt, random.Random(seed), seed + 1)
        assert set(d) == {"round_id", "title", "statement", "input", "answer_format",
                          "answer", "belt", "kind"}
        assert d["belt"] == belt and d["kind"] in riddles.kinds(belt)
        assert d["round_id"] == seed + 1
        assert d["title"].startswith(f"{belt.capitalize()} belt: ")
        assert "Answer with" in d["statement"]
        r = R.validate(d)  # validate reads only the public fields
        assert r.hash() == hashing.riddle_hash(r.public())
        fmt, a = d["answer_format"], d["answer"]
        assert fmt in hashing.ANSWER_FORMATS
        if fmt == "integer":
            assert isinstance(a, int) and not isinstance(a, bool)
            assert hashing.canonical_answer(a, fmt) == str(a)
            assert hashing.canonical_answer(str(a), fmt) == str(a)
        else:
            assert isinstance(a, str)
            assert hashing.canonical_answer(a, fmt) == a
        seen.add(d["kind"])
    # 30 seeds over at most 4 kinds: every kind of the belt shows up
    assert seen == set(riddles.kinds(belt))


@pytest.mark.parametrize("belt", riddles.BELTS)
def test_same_seed_same_riddle(belt):
    for seed in (0, 1, 17):
        a = riddles.generate(belt, random.Random(seed), 5)
        b = riddles.generate(belt, random.Random(seed), 5)
        assert a == b
    assert riddles.generate(belt, random.Random(1), 5) != riddles.generate(belt, random.Random(2), 5)


def test_generate_picks_kind_with_the_rng():
    rng = random.Random(3)
    expected = rng.choice(riddles.kinds("white"))
    assert riddles.generate("white", random.Random(3), 1)["kind"] == expected


# --------------------------------------------------------------------------
# independent recomputation of every kind from statement + input only

def _run_program(code):
    buf = io.StringIO()
    with contextlib.redirect_stdout(buf):
        exec(code, {})  # noqa: S102 - generated by our own templates
    lines = buf.getvalue().splitlines()
    assert len(lines) == 1
    return int(lines[0])


def _is_prime(n):
    if n < 2:
        return False
    d = 2
    while d * d <= n:
        if n % d == 0:
            return False
        d += 1
    return True


# Independent reference implementations of the blue-belt intents, keyed by
# the function name found in the buggy code.
def _ref_sum_to_n(n):
    return n * (n + 1) // 2


def _ref_count_evens(xs):
    return len([x for x in xs if x % 2 == 0])


def _ref_longest_run(xs):
    best = cur = 0
    prev = object()
    for x in xs:
        cur = cur + 1 if x == prev else 1
        prev = x
        best = max(best, cur)
    return best


def _ref_dot_mod(xs, ys, m):
    return sum(x * y for x, y in zip(xs, ys, strict=True)) % m


def _ref_odd_product(n):
    p = 1
    for i in range(1, n + 1):
        if i % 2 == 1:
            p *= i
    return p


def _ref_first_min_index(xs):
    return xs.index(min(xs))


def _ref_max_prefix_sum(xs):
    return max([0] + [sum(xs[:i + 1]) for i in range(len(xs))])


_BLUE_REFS = {
    "sum_to_n": _ref_sum_to_n,
    "count_evens": _ref_count_evens,
    "longest_run": _ref_longest_run,
    "dot_mod": _ref_dot_mod,
    "odd_product": _ref_odd_product,
    "first_min_index": _ref_first_min_index,
    "max_prefix_sum": _ref_max_prefix_sum,
}


def _blue_call(d):
    """Function name and literal args parsed from the buggy code + statement."""
    fname = re.search(r"^def (\w+)\(", d["input"], re.M).group(1)
    call = re.search(r"`(\w+\(.*\))`", d["statement"]).group(1)
    node = ast.parse(call, mode="eval").body
    assert isinstance(node, ast.Call) and node.func.id == fname
    return fname, [ast.literal_eval(a) for a in node.args]


def _recompute(d):
    kind, st, inp = d["kind"], d["statement"], d["input"]
    if kind == "sum_lines":
        return sum(int(x) for x in inp.splitlines())
    if kind == "count_letter":
        letter = re.search(r"the letter '(.)'", st).group(1)
        return sum(1 for c in inp if c == letter)
    if kind == "max_int":
        return max(int(x) for x in inp.splitlines())
    if kind == "longest_word":
        return max(map(len, inp.split(" ")))
    if kind == "reverse_string":
        return "".join(reversed(inp))
    if kind == "caesar_decode":
        shift = int(re.search(r"forward by (\d+) positions", st).group(1))
        return "".join(c if c == " " else chr((ord(c) - ord("a") - shift) % 26 + ord("a"))
                       for c in inp)
    if kind == "xor_bytes":
        return "%02x" % functools.reduce(lambda a, b: a ^ b, inp.encode("ascii"))
    if kind == "digit_sum":
        return sum(map(int, inp))
    if kind == "nth_prime":
        n, c, p = int(inp), 0, 1
        while c < n:
            p += 1
            if _is_prime(p):
                c += 1
        return p
    if kind == "collatz_steps":
        x, steps = int(inp), 0
        while x != 1:
            x = x // 2 if x % 2 == 0 else 3 * x + 1
            steps += 1
        return steps
    if kind == "program_output":
        return _run_program(inp)
    if kind == "recurrence_sum":
        m = re.search(r"a\(1\) = (\d+), a\(2\) = (\d+).*a\(n\) = \((\d+) \* a\(n-1\) \+ (\d+) "
                      r"\* a\(n-2\)\) mod (\d+)", st)
        a1, a2, p, q, mod = map(int, m.groups())
        n = int(inp)
        seq = [a1, a2]
        while len(seq) < n:
            seq.append((p * seq[-1] + q * seq[-2]) % mod)
        return sum(seq[:n]) % mod
    if kind == "pow_nonce":
        zeros = int(re.search(r"starts with (\d+) zero", st).group(1))
        n = 0
        while True:
            if hashlib.sha256((inp + str(n)).encode()).hexdigest()[:zeros] == "0" * zeros:
                return n
            n += 1
    if kind == "prime_count":
        limit = int(inp)
        flags = [True] * limit
        for i in range(2, limit):
            if flags[i]:
                for j in range(2 * i, limit, i):
                    flags[j] = False
        return len([i for i in range(2, limit) if flags[i]])
    if kind == "sha256_hex":
        return hashlib.sha256(inp.encode()).hexdigest()
    if kind == "fix_the_bug":
        fname, args = _blue_call(d)
        return _BLUE_REFS[fname](*args)
    raise AssertionError(f"no independent check for kind {kind!r}")


@pytest.mark.parametrize("belt,kind", ALL_KINDS)
def test_each_kind_recomputes_from_statement_and_input(belt, kind):
    for seed in range(4):
        d = riddles.generate_kind(kind, random.Random(seed), 1)
        assert d["belt"] == belt and d["kind"] == kind
        assert _recompute(d) == d["answer"], d


def test_program_output_prints_one_integer_and_has_no_imports():
    for seed in range(20):
        d = riddles.generate_kind("program_output", random.Random(seed), 1)
        assert "import" not in d["input"]
        assert 3 <= len(d["input"].strip().splitlines()) <= 8
        assert _run_program(d["input"]) == d["answer"]


def test_pow_nonce_is_the_smallest():
    d = riddles.generate_kind("pow_nonce", random.Random(5), 1)
    zeros = int(re.search(r"starts with (\d+) zero", d["statement"]).group(1))
    for n in range(d["answer"]):
        assert not hashlib.sha256(f"{d['input']}{n}".encode()).hexdigest().startswith("0" * zeros)
    assert hashlib.sha256(f"{d['input']}{d['answer']}".encode()).hexdigest().startswith("0" * zeros)


def test_blue_buggy_code_differs_from_correct_answer():
    seen = set()
    for seed in range(40):
        d = riddles.generate_kind("fix_the_bug", random.Random(seed), 1)
        fname, args = _blue_call(d)
        ns = {}
        exec(d["input"], ns)  # noqa: S102 - the buggy code as given to the solver
        buggy = ns[fname](*args)
        assert buggy != d["answer"], (fname, args)
        assert _BLUE_REFS[fname](*args) == d["answer"]
        seen.add(fname)
    assert len(seen) >= 3
