#!/usr/bin/env python3
"""Freeze full-fight fixtures from the Python combat engine.

Run only after the hand vectors in docs/combat.md §8 pass. The output is the
shared parity set for the independent C++ core and browser reader
(docs/model.md: at least 10,000 frozen full fights, no mismatches). Never
regenerate it to make a failing implementation green; a changed ruleset gets
a new file named after its digest.

Layout, all hex is lowercase and uses the protocol encodings (docs/protocol.md §2):
  fights[i].rounds[r] = [plan_A 7B, plan_B 7B, executed beats, end state A||B 16B]
  fights[i].outcome   = [winner "A"|"B"|null, result]
  traced[i]           = per-beat detail for the first TRACED fights
"""
from __future__ import annotations

import argparse
import json
import random
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "packages/qdojo/src"))

from qdojo.combat.codec import encode_plan, encode_state  # noqa: E402
from qdojo.combat.engine import new_fight, resolve_round  # noqa: E402
from qdojo.combat.rules import candidate_1  # noqa: E402
from qdojo.combat.types import ATTACKS, SUBMITTED, Action, Plan  # noqa: E402

OUT = ROOT / "packages/qdojo/tests/combat/fixtures"
TRACED = 200

STYLES = {
    "uniform": [1, 1, 1, 1, 1, 1],
    "aggressive": [4, 3, 1, 1, 2, 1],
    "defensive": [1, 1, 4, 3, 1, 2],
    "tired": [3, 3, 1, 1, 3, 0],      # drives exhaustion
    "resting": [1, 1, 1, 1, 1, 5],
}


def _plan(rng: random.Random, style: str, power_available: int) -> Plan:
    weights = STYLES[style]
    actions = rng.choices(SUBMITTED, weights=weights, k=6)
    slots = [i for i, a in enumerate(actions) if a in ATTACKS]
    slot = -1
    if power_available and slots and rng.random() < 0.4:
        slot = rng.choice(slots)
    return Plan.of(actions, slot)


def _side(t) -> dict:
    return {"after": encode_state(t.after).hex(), "effective": int(t.effective), "cost_paid": t.cost_paid,
            "base": t.base_damage, "dealt": t.computed_damage, "lost": t.actual_hp_lost,
            "strain": t.strain, "recovered": t.recovered, "reasons": [r.value for r in t.reasons]}


def generate(count: int, seed: int):
    rules = candidate_1()
    rng = random.Random(seed)
    fights, traced = [], []
    for i in range(count):
        styles = (rng.choice(list(STYLES)), rng.choice(list(STYLES)))
        state = new_fight(rules)
        rounds, detail = [], []
        while state.outcome is None:
            pa = _plan(rng, styles[0], state.a.power_available)
            pb = _plan(rng, styles[1], state.b.power_available)
            res = resolve_round(rules, state, pa, pb)
            rounds.append([encode_plan(pa).hex(), encode_plan(pb).hex(), res.executed,
                           (encode_state(res.end.a) + encode_state(res.end.b)).hex()])
            if i < TRACED:
                detail.append([[_side(b.a), _side(b.b)] for b in res.beats])
            state = res.end
        fights.append({"rounds": rounds, "outcome": [state.outcome.winner, state.outcome.result.value]})
        if i < TRACED:
            traced.append(detail)
    return rules, fights, traced


def main():
    p = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    p.add_argument("--count", type=int, default=10_000)
    p.add_argument("--seed", type=int, default=20260921)
    p.add_argument("--check", action="store_true", help="fail if the frozen file differs")
    args = p.parse_args()
    rules, fights, traced = generate(args.count, args.seed)
    doc = {
        "schema": "qdojo.combat.fight-fixtures.v1",
        "note": "Generated by scripts/combat-fixtures.py from the Python engine after hand vectors passed.",
        "ruleset_digest": rules.digest.hex(),
        "semantic_version": rules.semantic_version,
        "seed": args.seed,
        "action_ids": {a.name: int(a) for a in Action},
        "fights": fights,
        "traced": traced,
    }
    text = json.dumps(doc, separators=(",", ":")) + "\n"
    path = OUT / f"fights-{rules.digest.hex()[:16]}.json"
    if args.check:
        if path.read_text() != text:
            sys.exit(f"{path} drifted from the engine")
        print(f"{path.name}: {len(fights)} fights match")
        return
    OUT.mkdir(parents=True, exist_ok=True)
    path.write_text(text)
    print(f"wrote {path.relative_to(ROOT)}: {len(fights)} fights, {len(traced)} traced, {len(text)} bytes")


if __name__ == "__main__":
    main()
