#!/usr/bin/env python3
"""Build sample combat exports for the website and parity journals for the C++ port.

Runs NPC-driven bots on a fresh devnet (fake QU, synthetic identities):
ranked fights, a forfeit, a duel series and a cup; then writes
  apps/web/data/combat/v1/sample/...          (public export shape, labelled sample)
  packages/qdojo/tests/combat/fixtures/contract/*.journal   (inputs + final event digest)
Deterministic: identical output on every run.
"""
from __future__ import annotations

import datetime as dt
import shutil
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "packages/qdojo/src"))
sys.path.insert(0, str(ROOT / "packages/qdojo/tests"))

from qdojo.combat import export, npcs, store  # noqa: E402
from qdojo.combat.bot import Bot, Budget, policy_chooser  # noqa: E402
from qdojo.combat.codec import Op  # noqa: E402
from qdojo.combat.devnet import Devnet  # noqa: E402
from qdojo.combat.evaluate import SearchPlanner  # noqa: E402
from qdojo.combat.rules import candidate_1  # noqa: E402

RULES = candidate_1()
NOON = dt.datetime(2026, 9, 23, 12, tzinfo=dt.timezone.utc)
SAMPLE = ROOT / "apps/web/data/combat/v1/sample"
TRACES = ROOT / "packages/qdojo/tests/combat/fixtures/contract"


class FixedSalt:
    """Sample data must be reproducible, so its salts are derived, and labelled so.
    Live bots use secrets.token_bytes; never copy this."""

    def __init__(self, label):
        self.label, self.n = label, 0

    def __call__(self, k):
        from qdojo.hashing import sha256
        self.n += 1
        return sha256(b"qdojo/sample-salt/v1\0", self.label.encode(), self.n.to_bytes(8, "little"))[:k]


def season(tmp: Path):
    net = Devnet(tmp)
    lineup = {"tanuki": npcs.scout_v1, "kappa": npcs.mixed_v1, "oni": npcs.ROSTER["kicker-v1"].policy,
              "tengu": SearchPlanner(candidates=40, samples=6), "kitsune": npcs.ROSTER["jabber-v1"].policy}
    bots = []
    for label, pol in lineup.items():
        fid, owner = net.ensure_fighter(label)
        b = Bot(net.client(owner), RULES, fid, owner, owner, policy_chooser(RULES, pol, bytes(32)),
                Budget(ruleset_digest=RULES.digest.hex(), max_fights_per_day=1000, max_daily_committed=10**9,
                       max_daily_net_loss=10**9, stop_after_faults=10**6),
                tmp / "bots" / label, clock=lambda: NOON)
        b.salt_source = FixedSalt(label)
        bots.append(b)
    # "ronin" queues once and then never plays: its opponent wins by forfeit.
    ronin, ronin_owner = net.ensure_fighter("ronin")
    net.world.send(ronin_owner, Op.QUEUE_ENTER, 1000, fighter_id=ronin, auth_version=1,
                   ruleset_digest=RULES.digest, timing_profile_id=1, fee_profile_id=1, tier_id=1,
                   max_gap=200, expires_tick=net.world.tick + 240)
    for _ in range(1200):
        for b in bots:
            b.step()
        net.world.end()
    # A duel series between two of them, played by the same bots' choosers.
    w, c = net.world, net.world.contract
    a, d = bots[0], bots[3]
    while c.fighters[a.fighter_id].lock != "IDLE" or c.fighters[d.fighter_id].lock != "IDLE":
        for b in bots:
            b.step()
        w.end()
    r = w.send(a.wallet, Op.DUEL_OFFER, 5000, fighter_id=a.fighter_id, auth_version=1, opponent_id=d.fighter_id,
               ruleset_digest=RULES.digest, timing_profile_id=1, fee_profile_id=1, stake=5000, format=1,
               expires_tick=w.tick + 200)
    w.send(d.wallet, Op.DUEL_ACCEPT, 5000, offer_id=r.data["offer_id"], fighter_id=d.fighter_id, auth_version=1)
    for _ in range(600):
        for b in (a, d):
            b.step()
        w.end()
    net.save()
    return net


def main():
    tmp = Path(tempfile.mkdtemp(prefix="qdojo-sample-"))
    try:
        net = season(tmp / "net")
        c = net.world.contract
        net.world.check_conservation()
        if SAMPLE.exists():
            shutil.rmtree(SAMPLE)
        root = SAMPLE / "combat" / "v1"
        written = export.export_all(c, root)
        # Flatten: the sample lives at apps/web/data/combat/v1/sample/<files>.
        for p in written:
            dest = SAMPLE / p.relative_to(root)
            dest.parent.mkdir(parents=True, exist_ok=True)
            p.replace(dest)
        shutil.rmtree(SAMPLE / "combat")
        (SAMPLE / "README.md").write_text(
            "Sample combat export generated by scripts/combat-sample-data.py on a local devnet.\n"
            "Fake QU, synthetic identities, NPC-driven bots, derived salts. Not a deployment.\n")
        TRACES.mkdir(parents=True, exist_ok=True)
        store.write(TRACES / "season.journal", net.m, net.world.journal, c.event_digest)
        # Random traffic with rejections, faults, duels, transfers and service gaps.
        from combat.test_contract import ADMIN, DEV, HOUSE, SHARE
        from combat.test_contract_fuzz import traffic
        from qdojo.combat.contract import development_manifest
        from qdojo.combat.sim import World
        for seed in (1, 2):
            w = World(development_manifest(RULES, ADMIN, HOUSE, DEV, SHARE))
            w.mint(ADMIN, 10**9)
            traffic(w, 2000, seed=seed, check=False)
            w.check_conservation()
            store.write(TRACES / f"fuzz-{seed}.journal", w.manifest, w.journal, w.contract.event_digest)
        # Scripted cup/capacity/stranger scenarios (scenarios.journal).
        import runpy
        runpy.run_path(str(ROOT / "scripts/combat-contract-scenarios.py"))["main"](TRACES / "scenarios.journal")
        fights = len(c.fights)
        kinds = sorted({x.result["kind"] for x in c.contests.values() if x.result})
        print(f"sample: {fights} fights, contests {kinds}; journal {len(net.world.journal)} records")
        print(f"event digest {c.event_digest.hex()}")
    finally:
        shutil.rmtree(tmp, ignore_errors=True)


if __name__ == "__main__":
    main()
